//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirportMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AeroportEntities : DbContext
    {
        public AeroportEntities()
            : base("name=AeroportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<FlightInfo> FlightInfo { get; set; }
        public virtual DbSet<OrderFlight> OrderFlight { get; set; }
        public virtual DbSet<Passanger> Passanger { get; set; }
    }
}
