//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirportMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flight()
        {
            this.FlightInfo = new HashSet<FlightInfo>();
            this.OrderFlight = new HashSet<OrderFlight>();
        }
    
        public System.Guid Flight_ID { get; set; }
        public string FlightNumber { get; set; }
        public string Destination { get; set; }
        public System.DateTime Departure_DateTime { get; set; }
        public System.DateTime Arrival_DateTime { get; set; }
        public string Airline { get; set; }
        public string Terminal { get; set; }
        public string ClassSeats { get; set; }
        public int Gate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightInfo> FlightInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFlight> OrderFlight { get; set; }
    }
}
