//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAirportMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFlight
    {
        public System.Guid OrderFlight_ID { get; set; }
        public System.Guid Passanger_Info_ID { get; set; }
        public System.Guid Flight_Info_ID { get; set; }
        public System.DateTime DateTimeOrder { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passanger Passanger { get; set; }
    }
}
